export enum ActionType {
    NOOP = 1,

    // Profile
    SET_PROFILE = 10,
    UPDATE_LEVEL_DATA = 11,

    // Game
    SET_GAME_LEVEL = 100,
    SET_CRYSTALS = 101,
    ADD_CRYSTAL = 102,
    SET_CURRENT_LEVEL_STATS = 103,
    SET_RESULT_LEVEL_STATS = 104,
    SET_GAME_STATE = 105,
    SET_GAME_START_TIME = 106,
    SET_LEVEL_SELECT_VISIBLE = 107,

}